### ISSUE TITLE
Add support for approve policies

### ISSUE THREAD

**Issue by khasanovbi** [powerdot/tg-approval-test-action#3]
Hi, I suggest some additional settings:
1) GITHUB_USERNAME_TO_TELEGRAM_USER_ID - mapping a github user to a user in telegram:
```
GITHUB_USERNAME_TO_TELEGRAM_USER_ID: 
    powerdot: 12300303
    khasanovbi: 12300304
    githubuser: 12300305
```

2) ALLOWED_APPROVERS - a list of github users and teams that can approve the deployment
```
ALLOWED_APPROVERS:
   - powerdot
   - khasanovbi
```

3) EXCLUDE_WORKFLOW_INITIATOR_AS_APPROVER -  is a boolean that indicates if the workflow initiator (determined by the GITHUB_ACTOR environment variable) should be filtered from the final list of approvers.

4) SUPER_APPROVERS - a list of approvers that could ignore EXCLUDE_WORKFLOW_INITIATOR_AS_APPROVER boolean.
```
SUPER_APPROVERS:
   - khasanovbi
```
